language: python

python:
  - "2.7"

install:
  # Use system python, not virtualenv, because building the dependencies from source takes too long
  - deactivate # the virtualenv
  - time sudo apt-get install -qq python-numpy python-matplotlib

  # Install a ROOT binary that we custom-built in a 32-bit Ubuntu VM
  - time wget https://github.com/downloads/cdeil/travis_test/root_v5.34.02.Linux-Ubuntu32-gcc4.6_v02.tar.gz
  - time tar zxf root_v5.34.02.Linux-Ubuntu32-gcc4.6_v02.tar.gz
  - source root_v5.34.02.Linux-Ubuntu32-gcc4.6/bin/thisroot.sh
  #- echo "PATH = $PATH"
  #- echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"

  # Install rootpy
  - time python setup.py install --user

script:
  # Check if root and rootpy are properly installed
  - time root -l -q
  - time python -c 'import ROOT'
  - time python -c 'import rootpy'
  - time python -c 'import rootpy.types'
  # Now run the actual tests (from the installed version, not the local build dir)
  - pwd
  - cd ..
  - python -c 'import rootpy; print(rootpy.__file__)'
  - time python rootpy/examples/root2array/tree_to_array.py
  #- time nosetests
